### ISSUE TITLE
Support the bridge being a mailserver

### ISSUE THREAD

**Issue by turt2live** [kamax-io/matrix-appservice-email#2]
This could lead to simpler deployments, as all you'd have to do is set up an MX record.

Additionally, it would mean that inbound mail to a room (ie: mailing lists) could be handled more gracefully, as you could manage the email address for a specific room.

**Comment by maxidorius** [comment]
I'll mark this as wontfix, as the very little (theorical) added value really doesn't make up for all the various issues (spam, complexity of implementations).
I also don't see any situation that cannot be done with a regular e-mail server support.
