### ISSUE TITLE
Retry accepting invites if it initially fails

### ISSUE THREAD

**Issue by turt2live** [kamax-io/matrix-appservice-email#25]
Synapse has an annoying bug where the invite can hit the appservice/client before it is capable of responding to that invite, and often throws back either a 500 or "You are not invited to that room" error. To work around this, the best approach is to retry accepting the invite on some sort of schedule. I'd recommend max 5 retries, 30 seconds apart.

**Comment by maxidorius** [comment]
Given this is a synapse bug, it's up to them to fix their broken behaviour. No workaround will be added to the bridge for it.
